In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)

In [29]:
file = '/Users/mkapilev/Documents/Insight/Project_databases/Alternative_data_sets/demographic-snapshot-2015-16-to-2019-20-(public) (4).xlsx'
demographicDF = pd.read_excel(file, sheet_name='School')
demographicDF = demographicDF[demographicDF['Year'] == '2019-20']
demographicDF

DBN                               School Name     Year  \
4     01M015                 P.S. 015 Roberto Clemente  2019-20   
9     01M019                       P.S. 019 Asher Levy  2019-20   
14    01M020                      P.S. 020 Anna Silver  2019-20   
19    01M034            P.S. 034 Franklin D. Roosevelt  2019-20   
24    01M063                 The STAR Academy - P.S.63  2019-20   
...      ...                                       ...      ...   
9075  84X705        Family Life Academy Charter School  2019-20   
9080  84X706             Harriet Tubman Charter School  2019-20   
9085  84X717                      Icahn Charter School  2019-20   
9090  84X718  Bronx Charter School for Better Learning  2019-20   
9095  84X730         Bronx Charter School for the Arts  2019-20   

      Total Enrollment  Grade 3K+PK (Half Day & Full Day)  Grade K  Grade 1  \
4                  190                                 14       29       28   
9                  236                                 16       25       27   
14                 464                                 41       63       61   
19                 296                                 17       24       26   
24                 229                                 26       40       34   
...                ...                                ...      ...      ...   
9075               405                                  0      115       54   
9080               663                                  0       71       65   
9085               323                                  0       33       40   
9090               571                                 18      103       78   
9095               523                                  0       51       50   

      Grade 2  Grade 3  Grade 4  Grade 5  Grade 6  Grade 7  Grade 8  Grade 9  \
4          38       33       29       19        0        0        0        0   
9          39       45       42       42        0        0        0        0   
14         71       76       65       87        0        0        0        0   
19         16       18       21       43       43       40       48        0   
24         38       30       32       29        0        0        0        0   
...       ...      ...      ...      ...      ...      ...      ...      ...   
9075       76       55       53       52        0        0        0        0   
9080       83       77       78       87       71       68       63        0   
9085       40       41       38       36       36       32       27        0   
9090       80      101       97       94        0        0        0        0   
9095       53       52       55       49      107      106        0        0   

      Grade 10  Grade 11  Grade 12  # Female  % Female  # Male    % Male  \
4            0         0         0        94  0.494737      96  0.505263   
9            0         0         0       110  0.466102     126  0.533898   
14           0         0         0       233  0.502155     231  0.497845   
19           0         0         0       141  0.476351     155  0.523649   
24           0         0         0       104  0.454148     125  0.545852   
...        ...       ...       ...       ...       ...     ...       ...   
9075         0         0         0       226  0.558025     179  0.441975   
9080         0         0         0       358  0.539970     305  0.460030   
9085         0         0         0       168  0.520124     155  0.479876   
9090         0         0         0       316  0.553415     255  0.446585   
9095         0         0         0       280  0.535373     243  0.464627   

      # Asian   % Asian  # Black   % Black  # Hispanic  % Hispanic  \
4          27  0.142105       56  0.294737          96    0.505263   
9          11  0.046610       49  0.207627         148    0.627119   
14        120  0.258621       58  0.125000         239    0.515086   
19          7  0.023649      107  0.361486         172    0.581081   
24          9  0.039301       3

In [30]:
file = '/Users/mkapilev/Documents/Insight/Project_databases/Alternative_data_sets/peers/201819hs_sqr_StudentAchievement.xlsx'
achievementHighDF = pd.read_excel(file, sheet_name='Student Achievement')
achievementHighDF

DBN                                        School Name  School Type  \
0       NaN                                                NaN          NaN   
1    01M292                         Orchard Collegiate Academy  High School   
2    01M448                University Neighborhood High School  High School   
3    01M450                         East Side Community School  High School   
4    01M509                            Marta Valle High School  High School   
..      ...                                                ...          ...   
482  84X581               South Bronx Community Charter School  High School   
483  84X597  The Urban Assembly Charter School for Computer...  High School   
484  84X610                  Urban Dove Team Charter School II  High School   
485  84X703                   Bronx Preparatory Charter School  High School   
486  84X704                        KIPP Academy Charter School  High School   

    Student Achievement - Section Rating Student Achievement - Section Score  \
0                                    NaN                                 NaN   
1                         Meeting Target                                3.89   
2                       Exceeding Target                                4.11   
3                         Meeting Target                                3.99   
4                         Meeting Target                                3.27   
..                                   ...                                 ...   
482                                  NaN                                   .   
483                                  NaN                                   .   
484                                  NaN                                   .   
485                     Exceeding Target                                4.06   
486                       Meeting Target                                3.99   

    Metric Rating - 10+ Credits in 1st Year - All Students  \
0                                                  NaN       
1                                       Meeting Target       
2                                     Exceeding Target       
3                                       Meeting Target       
4                                     Exceeding Target       
..                                                 ...       
482                                                NaN       
483                                                NaN       
484                                                NaN       
485                                 Approaching Target       
486                                     Meeting Target       

    N count - 10+ Credits in 1st Year - All Students  \
0                                                NaN   
1                                                 66   
2                                                119   
3                                                 94   
4                                                 26   
..                                               ...   
482                                               77   
483                                              106   
484                                                .   
485                                              106   
486                                               73   

    Metric Value - 10+ Credits in 1st Year - All Students  \
0                                                  NaN      
1                                                0.864      
2                                                 0.95      
3                                                0.904      
4                                                0.962      
..                                                 ...      
482                                               N<15      
483                                              0.953      
484                                               N<15      
485                                              0.811      
486      

In [31]:
file = '/Users/mkapilev/Documents/Insight/Project_databases/Alternative_data_sets/peers/201819ems_sqr_StudentAchievement.xlsx'
achievementMiddleDF = pd.read_excel(file, sheet_name='Student Achievement')
achievementMiddleDF

DBN                               School Name School Type  \
0        NaN                                       NaN         NaN   
1     01M015                 P.S. 015 Roberto Clemente  Elementary   
2     01M019                       P.S. 019 Asher Levy  Elementary   
3     01M020                      P.S. 020 Anna Silver  Elementary   
4     01M034            P.S. 034 Franklin D. Roosevelt         K-8   
...      ...                                       ...         ...   
1289  84X705        Family Life Academy Charter School  Elementary   
1290  84X706             Harriet Tubman Charter School         K-8   
1291  84X717                      Icahn Charter School         K-8   
1292  84X718  Bronx Charter School for Better Learning  Elementary   
1293  84X730         Bronx Charter School for the Arts  Elementary   

     Student Achievement - Section Rating Student Achievement - Section Score  \
0                                     NaN                                 NaN   
1                        Exceeding Target                                4.86   
2                        Exceeding Target                                4.09   
3                          Meeting Target                                3.82   
4                      Not Meeting Target                                1.74   
...                                   ...                                 ...   
1289                   Approaching Target                                2.43   
1290                                  NaN                                   .   
1291                       Meeting Target                                3.76   
1292                       Meeting Target                                3.76   
1293                   Approaching Target                                2.26   

     Metric Rating - MS Adjusted Core Course Pass Rate of Former Students  \
0                                                   NaN                     
1                                        Meeting Target                     
2                                      Exceeding Target                     
3                                      Exceeding Target                     
4                                                   NaN                     
...                                                 ...                     
1289                                                NaN                     
1290                                                NaN                     
1291                                                NaN                     
1292                                   Exceeding Target                     
1293                                                NaN                     

     N count - MS Adjusted Core Course Pass Rate of Former Students  \
0                                                   NaN               
1                                                    21               
2                                                    37               
3                                                    60               
4                                                     .               
...                                                 ...               
1289                                                  3               
1290                                                  .               
1291                                                  .               
1292                                                 34               
1293                                                  6               

     Metric Value - MS Adjusted Core Course Pass Rate of Former Students  \
0                                                   NaN                    
1                                                 0.957                    
2                                                 0.988                    
3                                                 0.975                    
4                                    

In [32]:
a = achievementMiddleDF[['DBN', 'Student Achievement - Section Score']]
b = achievementHighDF[['DBN', 'Student Achievement - Section Score']]
achievementDF = pd.concat([a, b])
achievementDF

DBN Student Achievement - Section Score
0       NaN                                 NaN
1    01M015                                4.86
2    01M019                                4.09
3    01M020                                3.82
4    01M034                                1.74
..      ...                                 ...
482  84X581                                   .
483  84X597                                   .
484  84X610                                   .
485  84X703                                4.06
486  84X704                                3.99

[1781 rows x 2 columns]

In [58]:
joinedDF = demographicDF[['DBN', 'Economic Need Index']].merge(achievementDF, how='inner', left_on=['DBN'], right_on=['DBN'])
joinedDF

DBN Economic Need Index Student Achievement - Section Score
0     01M015            0.869011                                4.86
1     01M019            0.700085                                4.09
2     01M020            0.781916                                3.82
3     01M034           Above 95%                                1.74
4     01M063            0.781674                                3.15
...      ...                 ...                                 ...
1772  84X705            0.884186                                2.43
1773  84X706            0.877929                                   .
1774  84X717            0.821765                                3.76
1775  84X718            0.624517                                3.76
1776  84X730              0.8886                                2.26

[1777 rows x 3 columns]

In [61]:
def isfloat(value):
    try:
        float(value)
        return True
    except ValueError:
        return False

def valid(row):
    return isfloat(row['Economic Need Index']) and isfloat(row['Student Achievement - Section Score'])

def normalizeScore(row):
    return float(row['Student Achievement - Section Score']) / 5

joinedDF = joinedDF[joinedDF.apply(valid, axis=1)]
joinedDF['Student Achievement - Section Score Normalized'] = joinedDF.apply(normalizeScore, axis=1)
joinedDF

/Users/mkapilev/anaconda3/envs/turi/lib/python3.6/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app


DBN Economic Need Index Student Achievement - Section Score  \
0     01M015            0.869011                                4.86   
1     01M019            0.700085                                4.09   
2     01M020            0.781916                                3.82   
4     01M063            0.781674                                3.15   
5     01M064            0.910742                                4.15   
...      ...                 ...                                 ...   
1771  84X704            0.842267                                3.99   
1772  84X705            0.884186                                2.43   
1774  84X717            0.821765                                3.76   
1775  84X718            0.624517                                3.76   
1776  84X730              0.8886                                2.26   

      Student Achievement - Section Score Normalized  
0                                              0.972  
1                                              0.818  
2                                              0.764  
4                                              0.630  
5                                              0.830  
...                                              ...  
1771                                           0.798  
1772                                           0.486  
1774                                           0.752  
1775                                           0.752  
1776                                           0.452  

[1558 rows x 4 columns]

In [64]:
from sklearn.cluster import KMeans

X = joinedDF[['Economic Need Index', 'Student Achievement - Section Score Normalized']]

km = KMeans(
    n_clusters=5, init='random',
    n_init=10, max_iter=300, 
    tol=1e-04, random_state=0
)
y_km = km.fit_predict(X)

km.cluster_centers_

array([[0.8161978 , 0.84165579],
       [0.29745383, 0.79640237],
       [0.85970815, 0.65017937],
       [0.82753063, 0.48853453],
       [0.57578788, 0.72358242]])

In [65]:
clusterDF = joinedDF
clusterDF['Cluster'] = y_km
clusterDF

/Users/mkapilev/anaconda3/envs/turi/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


DBN Economic Need Index Student Achievement - Section Score  \
0     01M015            0.869011                                4.86   
1     01M019            0.700085                                4.09   
2     01M020            0.781916                                3.82   
4     01M063            0.781674                                3.15   
5     01M064            0.910742                                4.15   
...      ...                 ...                                 ...   
1771  84X704            0.842267                                3.99   
1772  84X705            0.884186                                2.43   
1774  84X717            0.821765                                3.76   
1775  84X718            0.624517                                3.76   
1776  84X730              0.8886                                2.26   

      Student Achievement - Section Score Normalized  Cluster  
0                                              0.972        0  
1                                              0.818        0  
2                                              0.764        0  
4                                              0.630        2  
5                                              0.830        0  
...                                              ...      ...  
1771                                           0.798        0  
1772                                           0.486        3  
1774                                           0.752        0  
1775                                           0.752        4  
1776                                           0.452        3  

[1558 rows x 5 columns]

In [69]:
pd.Series(y_km).value_counts()

2    444
3    336
0    336
4    273
1    169
dtype: int64

In [72]:
#Nearest Neighbors
from sklearn.neighbors import KDTree
import numpy as np
kdt = KDTree(X, leaf_size=40, metric='euclidean')

# find 10 closest schools given the target school
school = np.array([[0.869011, 0.972]])
kdt.query(school, k=10, return_distance=True)

(array([[3.72730255e-07, 7.12640604e-03, 1.01585749e-02, 1.25530328e-02,
         2.37558129e-02, 2.86308864e-02, 3.20120561e-02, 3.67701052e-02,
         3.72613633e-02, 4.19829105e-02]]),
 array([[   0,  454,  777,  853, 1490,  833,  889, 1527, 1545,  825]]))

In [75]:
#Nearest Neighbors
from sklearn.neighbors import NearestNeighbors
import numpy as np

school = np.array([[0.869011, 0.972]])
nbrs = NearestNeighbors(n_neighbors=10, algorithm='ball_tree').fit(X)
distances, indices = nbrs.kneighbors(school)
distances, indices

(array([[3.72730255e-07, 7.12640604e-03, 1.01585749e-02, 1.25530328e-02,
         2.37558129e-02, 2.86308864e-02, 3.20120561e-02, 3.67701052e-02,
         3.72613633e-02, 4.19829105e-02]]),
 array([[   0,  454,  777,  853, 1490,  833,  889, 1527, 1545,  825]]))